vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        dynamic_files:
            uri_prefix: /uploads/{file_type}
            upload_destination: "%kernel.project_dir%/public/uploads/{file_type}"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
