controllers_super_admin:
    resource: ../src/Controller/SuperAdmin/
    type: attribute
    name_prefix:  super_admin_
    prefix: /bornexus/admin
controllers_commercial_company:
    resource: ../src/Controller/CommercialCompany/
    type: attribute
    name_prefix:  commercial_company_
    prefix: /companies/admin
controllers:
    resource: ../src/Controller/Global/
    type: attribute